# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-03 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniurlapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miniurl',
            old_name='nb_acces',
            new_name='nb_access',
        ),
    ]
