# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-07 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniurlapp', '0003_auto_20171007_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=31)),
                ('moyenne', models.IntegerField(default=10)),
            ],
        ),
    ]
